// themes.js
window.AE_FONTS = [
    'Inter',
    'JetBrains Mono',
    'Roboto',
    'Montserrat',
    'Open Sans',
    'Orbitron',
    'Merriweather',
    'Special Elite',
    'Google Sans Code',
    'Space Grotesk',
    'Nunito',
    'Work Sans',
    'Recursive',
    'Manrope',
    'Source Sans Pro',
    'Coda'
];

window.AE_THEMES = {
    'LIGHT': {
        '--surface-primary': '#f4f4f5',
        '--surface-secondary': '#e4e4e7cb',
        '--surface-tertiary': '#e0e0e0',
        '--surface-inverse': '#e0e0e0',
        '--surface-variant': '#e0e0e0',
        '--text-primary': '#111827',
        '--text-secondary': '#4b5563',
        '--text-tertiary': '#9ca3af',        
        '--border-primary': '#d4d4d8',
        '--border-secondary': '#a1a1aa',
        '--border-tertiary': '#a1a1aa',
        '--accent-primary': '#0284c7',
        '--accent-secondary': '#475569',
        '--accent-tertiary': '#0284C7',
        '--accent-trigger': '#a78bfa',
        '--accent-action': '#2dd4bf',
        '--accent-prompt': '#4ade80',
        '--accent-logic': '#fb923c',
        '--accent-human': '#f472b6',
        '--accent-data': '#60a5fa',
        '--accent-hover': '#0284C7',
        '--surface-node': '#ffffff',
        '--surface-positive': '#059669',
        '--surface-destructive': '#c41c1ca8',
        '--surface-informational': '#0285c7cb',
        '--surface-navigational': '#4B5563',
        '--surface-warning': '#f59e0b',
        '--surface-error': '#ef4444',
        '--surface-neutral': '#6782a7',
        '--surface-popover': '#27272a',
        '--surface-success': '#22c55e',
        '--line-node': '#525252',
        '--pattern-color': 'transparent',
        '--bg-image': 'none', 
        '--bg-attachment': 'scroll'
    },
};